apiVersion: v1
kind: Service
metadata:
  name: datasamudayastandalone
  labels:
    app: datasamudayastandalone
spec:
  type: NodePort
  selector:
    app: datasamudayastandalone
  ports:
    - name: streamproto
      protocol: TCP
      port: 22222
      targetPort: 22222
      nodePort: 32000
    - name: streamweb
      protocol: TCP
      port: 22223
      targetPort: 22223
      nodePort: 32001
    - name: mrproto
      protocol: TCP
      port: 11111
      targetPort: 11111
      nodePort: 32002
    - name: mrweb
      protocol: TCP
      port: 11112
      targetPort: 11112
      nodePort: 32003
    - name: sqlstream
      protocol: TCP
      port: 12123
      targetPort: 12123
      nodePort: 32004
    - name: sqlshell
      protocol: TCP
      port: 12124
      targetPort: 12124
      nodePort: 32005
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    app: datasamudayanamenode
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: datasamudayanamenode
  ports:
    - name: hdfsname
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: hdfsweb
      protocol: TCP
      port: 9870
      targetPort: 9870
---
apiVersion: v1
kind: Service
metadata:
  name: zoo
  labels:
    app: datasamudayazk
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: datasamudayazk
  ports:
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181