apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datasamudayazk
  labels:
    app: datasamudayazk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasamudayazk
  template:
    metadata:
      labels:
        app: datasamudayazk
    spec:
      containers:
        - name: datasamudayazk
          image: arunsrajan/datasamudayazk:latest          
          ports:
            - containerPort: 2181
              name: zkport
          volumeMounts:
            - name: hdfsdatanode
              mountPath: /opt/dockershare/data
  volumeClaimTemplates:
        - metadata:
            name: hdfsdatanode
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datasamudayastandalone
  labels:
    app: datasamudayastandalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasamudayastandalone
  template:
    metadata:
      labels:
        app: datasamudayastandalone
    spec:
      containers:
        - name: datasamudayastandalone
          image: arunsrajan/datasamudayastandalone:latest
          env:
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: 'false'
            - name: HDFS_CONF_dfs_datanode_data_dir
              value: /opt/dockershare/data
            - name: ZKHOSTPORT
              value: zoo:2181
            - name: TEHOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TEPORT
              value: "10101"
            - name: NODEPORT
              value: "12121"
            - name: TSSHOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TSSPORT
              value: "22222"
            - name: TSHOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TSPORT
              value: "11111"
          ports:
            - containerPort: 22222
              name: streamproto
            - containerPort: 22223
              name: streamweb
            - containerPort: 11111
              name: mrproto
            - containerPort: 11112
              name: mrweb
            - containerPort: 12123
              name: sqlstream
            - containerPort: 12124
              name: sqlshell
          volumeMounts:
            - name: hdfsdatanode
              mountPath: /opt/dockershare/data
  volumeClaimTemplates:
        - metadata:
            name: hdfsdatanode
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi